// Generated from webui/error_registry.to_json(); keep in sync via tests.
export const ERROR_CODES = [
  "ai_key_invalid",
  "ai_missing_job",
  "ai_network_error",
  "ai_not_configured",
  "ai_quota_exhausted",
  "ai_rate_limited",
  "applied_at_in_future",
  "applied_at_invalid",
  "applied_at_required",
  "auth_failed",
  "city_mapping_missing",
  "city_mapping_unavailable",
  "detail_invalid",
  "detail_timeout",
  "filter_schema_version_mismatch",
  "filter_snapshot_incompatible",
  "follow_up_before_application",
  "idempotency_conflict",
  "internal_error",
  "invalid_action",
  "invalid_action_payload",
  "invalid_limit",
  "invalid_response",
  "job_identity_conflict",
  "job_identity_incomplete",
  "job_not_found",
  "job_offline",
  "legacy_platform_not_supported",
  "login_space_conflict",
  "migration_backup_failed",
  "migration_failed",
  "mixed_platform_jobs",
  "network_error",
  "non_pending_platform_job_ids",
  "not_found",
  "persistence_failed",
  "platform_disabled",
  "platform_schema_unavailable",
  "platform_url_mismatch",
  "platform_validation_failed",
  "profile_not_found",
  "quota_exhausted",
  "rate_limited",
  "reminder_not_eligible",
  "result_not_clearable",
  "resumed",
  "run_identity_conflict",
  "search_filters_not_supported",
  "server_error",
  "source_account_restricted",
  "source_blocked",
  "source_cdp_unavailable",
  "source_input_drift",
  "source_invalid_output",
  "source_login_required",
  "source_not_found",
  "source_rate_limited",
  "source_request_limit_exceeded",
  "source_result_write_failed",
  "source_status_unclear",
  "source_timeout",
  "source_unknown_error",
  "source_unreachable",
  "source_verification_required",
  "state_precondition_failed",
  "task_input_mismatch",
  "timeout",
  "truncated",
  "tuning_platform_mismatch",
  "unknown_error",
  "user_finished",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const ERROR_MESSAGES: Record<string, string> = {
  "ai_key_invalid": "AI 密钥失效或鉴权失败",
  "ai_missing_job": "AI 漏回单个岗位判定",
  "ai_network_error": "AI 网络或服务故障",
  "ai_not_configured": "AI 未配置，请先设置 API 地址和密钥",
  "ai_quota_exhausted": "AI 额度已耗尽",
  "ai_rate_limited": "AI 服务限流，请求过于频繁",
  "applied_at_in_future": "applied_at_in_future",
  "applied_at_invalid": "applied_at_invalid",
  "applied_at_required": "applied_at_required",
  "auth_failed": "API 密钥无效或已过期，请检查 AI 设置",
  "city_mapping_missing": "city_mapping_missing",
  "city_mapping_unavailable": "city_mapping_unavailable",
  "detail_invalid": "详情结构无效（登录墙/导航壳/空壳）",
  "detail_timeout": "单岗位详情抓取超时",
  "filter_schema_version_mismatch": "filter_schema_version_mismatch",
  "filter_snapshot_incompatible": "filter_snapshot_incompatible",
  "follow_up_before_application": "follow_up_before_application",
  "idempotency_conflict": "idempotency_conflict",
  "internal_error": "内部状态或持久化错误",
  "invalid_action": "invalid_action",
  "invalid_action_payload": "invalid_action_payload",
  "invalid_limit": "invalid_limit",
  "invalid_response": "AI 返回了无法解析的内容，请重试",
  "job_identity_conflict": "job_identity_conflict",
  "job_identity_incomplete": "job_identity_incomplete",
  "job_not_found": "job_not_found",
  "job_offline": "岗位已下架",
  "legacy_platform_not_supported": "legacy_platform_not_supported",
  "login_space_conflict": "login_space_conflict",
  "migration_backup_failed": "migration_backup_failed",
  "migration_failed": "migration_failed",
  "mixed_platform_jobs": "mixed_platform_jobs",
  "network_error": "无法连接 AI 服务，请检查网络与地址配置",
  "non_pending_platform_job_ids": "non_pending_platform_job_ids",
  "not_found": "not_found",
  "persistence_failed": "persistence_failed",
  "platform_disabled": "platform_disabled",
  "platform_schema_unavailable": "platform_schema_unavailable",
  "platform_url_mismatch": "platform_url_mismatch",
  "platform_validation_failed": "platform_validation_failed",
  "profile_not_found": "profile_not_found",
  "quota_exhausted": "AI 额度已用完，请明天再试或更换 API 密钥",
  "rate_limited": "AI 服务限流（免费额度），请稍候再试",
  "reminder_not_eligible": "reminder_not_eligible",
  "result_not_clearable": "result_not_clearable",
  "resumed": "任务已恢复",
  "run_identity_conflict": "run_identity_conflict",
  "search_filters_not_supported": "search_filters_not_supported",
  "server_error": "AI 服务暂时不可用，请稍后重试",
  "source_account_restricted": "确认账号/平台受限",
  "source_blocked": "IP 级风控拦截",
  "source_cdp_unavailable": "连不上调试浏览器",
  "source_input_drift": "输入快照与执行不一致",
  "source_invalid_output": "输入校验失败或页面解析异常",
  "source_login_required": "登录已失效，需重新登录",
  "source_not_found": "岗位不存在或已下架",
  "source_rate_limited": "账号/操作频繁被限流",
  "source_request_limit_exceeded": "本轮抓取请求数已达上限",
  "source_result_write_failed": "结果文件写入失败",
  "source_status_unclear": "暂时无法确认平台状态",
  "source_timeout": "抓取超时",
  "source_unknown_error": "未知抓取错误",
  "source_unreachable": "抓取脚本不可用",
  "source_verification_required": "触发验证码/滑块，需手动完成",
  "state_precondition_failed": "state_precondition_failed",
  "task_input_mismatch": "task_input_mismatch",
  "timeout": "AI 响应超时，请稍后重试",
  "truncated": "AI 返回内容被截断，请重试（可减小单批数量）",
  "tuning_platform_mismatch": "tuning_platform_mismatch",
  "unknown_error": "unknown_error",
  "user_finished": "用户主动结束",
};
